# Generated by Django 3.1 on 2020-08-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.TextField(max_length=255)),
                ('lastname', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.TextField()),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('company', models.TextField(max_length=100)),
                ('strip_id', models.TextField(blank=True)),
                ('product_id', models.TextField(blank=True)),
                ('subscription_id', models.TextField(blank=True)),
            ],
        ),
    ]
